import React from 'react';
import { FlatList, StyleSheet, Text, View } from 'react-native';


export default function RecipesScreen() {
    return (
      <View style={styles.container}>
        <FlatList
          data={[
            {key: 'Devin'},
            {key: 'Dan'},
            {key: 'Dominic'},
            {key: 'Jackson'},
            {key: 'James'},
            {key: 'Joel'},
            {key: 'John'},
            {key: 'Jillian'},
            {key: 'Jimmy'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
            {key: 'Julie'},
          ]}
          renderItem={({item}) => <Text style={styles.item}>{item.key}</Text>}
        />
      </View>
    );
}

RecipesScreen.navigationOptions = {
  header: null,
};
const styles = StyleSheet.create({
});

